/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JspC/ApacheTomcat9
 * Generated at: 2025-02-21 01:18:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.Account;
import controller.Controller;
import model.Room;
import model.D_Feedback;
import model.Room_type;
import java.util.Set;
import java.util.List;
import java.util.LinkedList;
import java.util.ArrayList;
import model.Blog;
import java.util.HashMap;
import java.util.Map;
import model.Hotel;

public final class viewFeedback_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(18);
    _jspx_imports_classes.add("model.Room_type");
    _jspx_imports_classes.add("model.Account");
    _jspx_imports_classes.add("model.Blog");
    _jspx_imports_classes.add("java.util.Set");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("controller.Controller");
    _jspx_imports_classes.add("model.D_Feedback");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.Room");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("model.Hotel");
    _jspx_imports_classes.add("java.util.LinkedList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n<!-- JSP Start -->\r\n");

    int cPage = (Integer) request.getAttribute("cPage");
    int maxPage = (Integer) request.getAttribute("maxPage");
    int sr = (Integer) request.getAttribute("sr");
    Account account = (Account) session.getAttribute("acc");
    int role_ID = 6;
    Map<Integer, Hotel> listHotels = (Map<Integer, Hotel>) request.getAttribute("listHotels");
    Map<Integer, Blog> listAbout = (Map<Integer, Blog>) request.getAttribute("listAbout");
    Map<Integer, Blog> listNews = (Map<Integer, Blog>) request.getAttribute("listNews");
    Map<Integer, Blog> listReview = (Map<Integer, Blog>) request.getAttribute("listReview");
    Map<Integer, Blog> listGuide = (Map<Integer, Blog>) request.getAttribute("listGuide");
    Map<Integer, Room_type> listRoomType = (Map<Integer, Room_type>) request.getAttribute("listRoomType");
    Map<Integer, D_Feedback> listFeedBack = (Map<Integer, D_Feedback>) request.getAttribute("listFeedBack");
    Map<Integer, List<Room>> ListRoomOfHotels = (Map<Integer, List<Room>>) request.getAttribute("ListRoomOfHotels");
    Controller controller = new Controller();
    if (account != null) {
        role_ID = account.getRole_ID();
    }
    if (listHotels == null) {
        response.sendRedirect("home");
    } else {
        List<Integer> keyHotels = new ArrayList<>(listHotels.keySet());
        List<Integer> keyRoomType = new ArrayList<>(listRoomType.keySet());
        List<Integer> keyFeedback = new ArrayList<>(listFeedBack.keySet());

      out.write("\r\n<!-- JSP End -->\r\n\r\n\r\n<!DOCTYPE html>\r\n<html lang=\"en\">\r\n\r\n    <head>\r\n        <meta charset=\"utf-8\">\r\n        <title>Hotelier - Hotel HTML Template</title>\r\n        <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n        <meta content=\"\" name=\"keywords\">\r\n        <meta content=\"\" name=\"description\">\r\n\r\n        <!-- Favicon -->\r\n        <link href=\"img/favicon.ico\" rel=\"icon\">\r\n\r\n        <!-- Google Web Fonts -->\r\n        <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n        <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n        <link href=\"https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&family=Montserrat:wght@400;500;600;700&display=swap\" rel=\"stylesheet\">  \r\n\r\n        <!-- Icon Font Stylesheet -->\r\n        <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\" rel=\"stylesheet\">\r\n        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n        <!-- Libraries Stylesheet -->\r\n        <link href=\"lib/animate/animate.min.css\" rel=\"stylesheet\">\r\n        <link href=\"lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n        <link href=\"lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css\" rel=\"stylesheet\" />\r\n\r\n        <!-- Customized Bootstrap Stylesheet -->\r\n        <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n\r\n        <!-- Template Stylesheet -->\r\n        <link href=\"css/style.css\" rel=\"stylesheet\">\r\n\r\n\r\n\r\n    </head>\r\n\r\n    <body>\r\n        <div class=\"container-xxl bg-white p-0\">\r\n            <!-- Spinner Start -->\r\n            <div id=\"spinner\" class=\"show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center\">\r\n                <div class=\"spinner-border text-primary\" style=\"width: 3rem; height: 3rem;\" role=\"status\">\r\n                    <span class=\"sr-only\">Loading...</span>\r\n                </div>\r\n            </div>\r\n            <!-- Spinner End -->\r\n");
      out.write("\r\n            <!-- Header Start -->\r\n            <div class=\"container-fluid bg-dark px-0\">\r\n                <div class=\"row gx-0\">\r\n                    <div class=\"col-lg-3 bg-dark d-none d-lg-block\">\r\n                        <a href=\"home\" class=\"navbar-brand w-100 h-100 m-0 p-0 d-flex align-items-center justify-content-center\">\r\n                            <h1 class=\"m-0 text-primary text-uppercase\">Hotelier</h1>\r\n                        </a>\r\n                    </div>\r\n                    <div class=\"col-lg-9\">\r\n                        <div class=\"row gx-0 bg-white d-none d-lg-flex\">\r\n                            <div class=\"col-lg-7 px-5 text-start\">\r\n                                <div class=\"h-100 d-inline-flex align-items-center py-2 me-4\">\r\n                                    <i class=\"fa fa-envelope text-primary me-2\"></i>\r\n                                    <p class=\"mb-0\">  ");
      out.print( listHotels.get(keyHotels.get(0)).getEmail());
      out.write("  </p> <!-- get email of first hotel-->\r\n                                </div>\r\n                                <div class=\"h-100 d-inline-flex align-items-center py-2\">\r\n                                    <i class=\"fa fa-phone-alt text-primary me-2\"></i>\r\n                                    <p class=\"mb-0\"> ");
      out.print( listHotels.get(keyHotels.get(0)).getHotline());
      out.write("  </p> <!-- get hotline of first hotel-->\r\n                                </div>\r\n                            </div>\r\n                            <div class=\"col-lg-5 px-5 text-end\">\r\n                                <div class=\"d-inline-flex align-items-center py-2\">\r\n                                    <a class=\"me-3\" href=\"\"><i class=\"fab fa-facebook-f\"></i></a>\r\n                                    <a class=\"me-3\" href=\"\"><i class=\"fab fa-twitter\"></i></a>\r\n                                    <a class=\"me-3\" href=\"\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n                                    <a class=\"me-3\" href=\"\"><i class=\"fab fa-instagram\"></i></a>\r\n                                    <a class=\"\" href=\"\"><i class=\"fab fa-youtube\"></i></a>\r\n                                </div>\r\n                            </div>\r\n                        </div>\r\n                        <nav class=\"navbar navbar-expand-lg bg-dark navbar-dark p-3 p-lg-0\">\r\n                            <a href=\"home\" class=\"navbar-brand d-block d-lg-none\">\r\n");
      out.write("                                <h1 class=\"m-0 text-primary text-uppercase\">Hotelier</h1>\r\n                            </a>\r\n                            <button type=\"button\" class=\"navbar-toggler\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarCollapse\">\r\n                                <span class=\"navbar-toggler-icon\"></span>\r\n                            </button>\r\n                            <div class=\"collapse navbar-collapse justify-content-between\" id=\"navbarCollapse\">\r\n                                <div class=\"navbar-nav mr-auto py-0\">\r\n                                    <a href=\"home\" class=\"nav-item nav-link active\">Home</a>\r\n                                    <a href=\"home\" class=\"nav-item nav-link\">Hotels</a>\r\n                                    <a href=\"viewFeedback\" class=\"nav-item nav-link\">Feedback</a>\r\n                                    <a href=\"viewBlog\" class=\"nav-item nav-link\">Blog</a>\r\n\r\n                                </div>\r\n                                ");
if (role_ID == 6) {
                                
      out.write("\r\n                                <div class=\"d-flex\">\r\n                                    <a href=\"login?tab=register\" class=\"btn btn-secondary rounded-0 py-4 px-md-5 d-none d-lg-block\">\r\n                                        REGISTER\r\n                                        <i class=\"fa fa-user ms-3\"></i>\r\n                                    </a>\r\n                                    <a href=\"login\" class=\"btn btn-primary rounded-0 py-4 px-md-5 d-none d-lg-block\">\r\n                                        LOGIN\r\n                                        <i class=\"fa fa-user ms-3\"></i>\r\n                                    </a>\r\n                                </div>\r\n                                ");
} else {
      out.write("\r\n                                <div class=\"nav-item dropdown\">\r\n                                    <a href=\"\" class=\"btn btn-primary rounded-0 py-4 px-md-5 d-none d-lg-block \">");
      out.print( account.getUsername());
      out.write("<i class=\"fa fa-user ms-3\"></i></a>\r\n                                    <div class=\"dropdown-menu rounded-0 m-0\">\r\n                                        <a href=\"logout\" class=\"dropdown-item\">LOG OUT</i></a>\r\n                                    </div>\r\n                                </div>\r\n                                ");
}
      out.write("\r\n                            </div>\r\n                        </nav>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n            <!-- Header End -->\r\n\r\n\r\n            <!-- Feedback list Start -->\r\n            <div class=\"container d-flex justify-content-center mt-3 mb-3\">\r\n                <h1 class=\"section-title text-center text-primary text-uppercase\" style=\"text-align: center\">FEEDBACK</h1>\r\n            </div>\r\n            <div>\r\n                <div class=\"d-flex mt-3 mb-3 justify-content-around align-items-lg-center\">\r\n\r\n                    <form action=\"viewFeedback\" method=\"post\">\r\n                        <div><h6>Star rate: </h6>\r\n                            <select name=\"sr\" id=\"number\">\r\n                                <option value=\"0\" ");
 if (sr == 0) {
                                        out.println("selected");
                                    }
      out.write(">All</option>\r\n                                <option value=\"5\" ");
 if (sr == 5) {
                                        out.println("selected");
                                    }
      out.write(">5</option>\r\n                                <option value=\"4\" ");
 if (sr == 4) {
                                        out.println("selected");
                                    }
      out.write(">4</option>\r\n                                <option value=\"3\" ");
 if (sr == 3) {
                                        out.println("selected");
                                    }
      out.write(">3</option>\r\n                                <option value=\"2\" ");
 if (sr == 2) {
                                        out.println("selected");
                                    }
      out.write(">2</option>\r\n                                <option value=\"1\" ");
 if (sr == 1) {
                                        out.println("selected");
                                    }
      out.write(">1</option>\r\n                            </select></div>\r\n                        <div><h6>Page: <input type=\"number\" name=\"cPage\" value=\"");
      out.print(cPage);
      out.write("\"/>  / ");
      out.print(maxPage);
      out.write("</h6>\r\n                        </div>\r\n                        <button type=\"submit\">Select</button></form>\r\n                </div>\r\n            </div>\r\n            <table class=\"col-12\">\r\n                <tbody>\r\n                    ");

                        keyFeedback = controller.D_getFeedbackListByStarRate(sr, listFeedBack);
                        int numOfFeedback = 0;
                        int numSkip = 0;
                        for (Integer key : keyFeedback) {
                            numSkip++;
                            if (numSkip < (cPage - 1) * 10) {
                                continue;
                            }
                            numOfFeedback++;
                            if (numOfFeedback > 10) {
                                break;
                            }
                    
      out.write("\r\n                    <tr class=\"border-primary m-5\">\r\n                        <td class=\"border-end me-3 pe-3\"> <div class=\"d-flex justify-content-start\"> <i class=\"fa fa-user fa-2x text-primary mb-2\">  </i> <h6 class=\"fw-bold mb-1\">");
      out.print( listFeedBack.get(key).getUsername());
      out.write("</h6> </div></td>\r\n                        <td class=\"border-end me-3 pe-3\"> <i class=\"fa fa-hotel text-secondary mb-2\"><small>  ");
      out.print( listFeedBack.get(key).getHotelname());
      out.write("</small></td>\r\n                        <td class=\"border-end me-3 pe-3\"><div class=\"ps-2\">\r\n                                ");
for (int i = 1; i <= listFeedBack.get(key).getRate(); i++) {
      out.write("\r\n                                <small class=\"fa fa-star text-primary\"></small>\r\n                                ");
}
      out.write("\r\n                                ");
for (int i = 5; i > listFeedBack.get(key).getRate(); i--) {
      out.write("\r\n                                <small class=\"fa fa-star text-secondary\"></small>\r\n                                ");
}
      out.write("\r\n                            </div></td>\r\n\r\n                        <td class=\"border-end me-3 pe-3\">");
      out.print( listFeedBack.get(key).getContent());
      out.write("</td>\r\n                    </tr>\r\n\r\n                    ");
}
                        if (keyFeedback == null || keyFeedback.isEmpty()) {
                    
      out.write("<h2> Feedback list is empty! </h2>");

                        }
                
      out.write("\r\n\r\n\r\n                </tbody>\r\n            </table>\r\n        </div>\r\n        <!-- Feedback list End -->     \r\n\r\n\r\n        <!-- Footer Start -->\r\n        <div class=\"container-fluid bg-dark text-light footer fadeIn d-flex align-items-start py-5\" style=\"margin-top: 5px\">\r\n            <div class=\"container pb-5\" >\r\n                <div class=\"row g-5 align-items-start justify-content-end\" >\r\n\r\n                    <div class=\"col-md-6 col-lg-3\" \">\r\n                        <h6 class=\"section-title text-start text-primary text-uppercase mb-4\">Contact</h6>\r\n                        <p class=\"mb-2\">");
      out.print( listHotels.get(1).getName());
      out.write("</p>\r\n                        <p class=\"mb-2\"><i class=\"fa fa-map-marker-alt me-3\"></i>");
      out.print( listHotels.get(1).getAddress());
      out.write("</p>\r\n                        <p class=\"mb-2\"><i class=\"fa fa-phone-alt me-3\"></i>");
      out.print( listHotels.get(1).getHotline());
      out.write("</p>\r\n                        <p class=\"mb-2\"><i class=\"fa fa-envelope me-3 numberDropdown\"></i>");
      out.print( listHotels.get(1).getEmail());
      out.write("</p>\r\n                        <div class=\"d-flex pt-2\">\r\n                            <a class=\"btn btn-outline-light btn-social\" href=\"\"><i class=\"fab fa-twitter\"></i></a>\r\n                            <a class=\"btn btn-outline-light btn-social\" href=\"\"><i class=\"fab fa-facebook-f\"></i></a>\r\n                            <a class=\"btn btn-outline-light btn-social\" href=\"\"><i class=\"fab fa-youtube\"></i></a>\r\n                            <a class=\"btn btn-outline-light btn-social\" href=\"\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n                        </div>\r\n                    </div>\r\n                    <div class=\"col-lg-5 col-md-12\">\r\n                        <div class=\"row gy-5 g-4\">\r\n                            <div class=\"col-md-6\">\r\n                                <h6 class=\" section-title text-start text-primary text-uppercase mb-4\">Company</h6>\r\n                                <a class=\"btn btn-link\" href=\"\">About Us</a>\r\n                                <a class=\"btn btn-link\" href=\"\">Contact Us</a>\r\n                                <a class=\"btn btn-link\" href=\"\">Privacy Policy</a>\r\n");
      out.write("                                <a class=\"btn btn-link\" href=\"\">Terms & Condition</a>\r\n                                <a class=\"btn btn-link\" href=\"\">Support</a>\r\n                            </div>\r\n                            <div class=\"col-md-6\">\r\n                                <h6 class=\"section-title text-start text-primary text-uppercase mb-4\">Services</h6>\r\n                                <a class=\"btn btn-link\" href=\"\">Food & Restaurant</a>\r\n                                <a class=\"btn btn-link\" href=\"\">Spa & Fitness</a>\r\n                                <a class=\"btn btn-link\" href=\"\">Sports & Gaming</a>\r\n                                <a class=\"btn btn-link\" href=\"\">Event & Party</a>\r\n                                <a class=\"btn btn-link\" href=\"\">GYM & Yoga</a>\r\n                            </div>\r\n                        </div>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <!-- Footer End -->\r\n\r\n\r\n        <!-- Back to Top -->\r\n        <a href=\"#\" class=\"btn btn-lg btn-primary btn-lg-square back-to-top\"><i class=\"bi bi-arrow-up\"></i></a>\r\n");
      out.write("    </div>\r\n\r\n    <!-- JavaScript Libraries -->\r\n    <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n    <script src=\"lib/wow/wow.min.js\"></script>\r\n    <script src=\"lib/easing/easing.min.js\"></script>\r\n    <script src=\"lib/waypoints/waypoints.min.js\"></script>\r\n    <script src=\"lib/counterup/counterup.min.js\"></script>\r\n    <script src=\"lib/owlcarousel/owl.carousel.min.js\"></script>\r\n    <script src=\"lib/tempusdominus/js/moment.min.js\"></script>\r\n    <script src=\"lib/tempusdominus/js/moment-timezone.min.js\"></script>\r\n    <script src=\"lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js\"></script>\r\n\r\n    <!-- Template Javascript -->\r\n    <script src=\"js/main.js\"></script>\r\n\r\n</body>\r\n\r\n</html>\r\n");
}
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
